--- #YAML:1.0
name:               Dancer-Plugin-FormValidator
version:            0.4
abstract:           easy validates user input (usually from an HTML form)
author:
    - Natal Ngétal <hobbestig@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:               1.175
    Data::FormValidator:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
