---
abstract: 'Easy validates user input (usually from an HTML form) based on input profile for Dancer applications.'
author:
  - 'Natal Ngétal'
build_requires:
  Dancer::Test: 0
  Data::Dumper: 0
  JSON::Syck: 0
  Module::Build: 0.3601
  Test::More: 0
  YAML::Syck: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-FormValidator
requires:
  Dancer: 1.2001
  Dancer::Exception: 0
  Dancer::Plugin: 0
  Data::FormValidator: 0
  Module::Load: 0
  perl: 5.010
  strict: 0
  warnings: 0
version: 1.131620
